---
http_interactions:
- request:
    method: put
    uri: http://backend:5352/source/home:tom:Staging:XYZ/_config?user=factory%20bot
    body:
      encoding: UTF-8
      string: 'Prefer: foo'
    headers:
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
      User-Agent:
      - Ruby
  response:
    status:
      code: 200
      message: OK
    headers:
      Content-Type:
      - text/xml
      Cache-Control:
      - no-cache
      Connection:
      - close
      Content-Length:
      - '21'
    body:
      encoding: UTF-8
      string: '<status code="ok" />

'
  recorded_at: Tue, 31 Oct 2023 17:12:08 GMT
- request:
    method: get
    uri: http://backend:5352/source/home:tom:Staging:XYZ/_config
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
      User-Agent:
      - Ruby
  response:
    status:
      code: 200
      message: OK
    headers:
      Content-Type:
      - text/plain
      Cache-Control:
      - no-cache
      Connection:
      - close
      Content-Length:
      - '11'
    body:
      encoding: UTF-8
      string: 'Prefer: foo'
  recorded_at: Tue, 31 Oct 2023 17:12:09 GMT
- request:
    method: put
    uri: http://backend:5352/source/home:tom:new_project/_config?comment=Copying%20project%20home:tom:Staging:XYZ&user=tom
    body:
      encoding: UTF-8
      string: 'Prefer: foo'
    headers:
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
      User-Agent:
      - Ruby
  response:
    status:
      code: 200
      message: OK
    headers:
      Content-Type:
      - text/xml
      Cache-Control:
      - no-cache
      Connection:
      - close
      Content-Length:
      - '21'
    body:
      encoding: UTF-8
      string: '<status code="ok" />

'
  recorded_at: Tue, 31 Oct 2023 17:12:12 GMT
- request:
    method: get
    uri: http://backend:5352/source/home:tom:new_project/_config
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
      User-Agent:
      - Ruby
  response:
    status:
      code: 200
      message: OK
    headers:
      Content-Type:
      - text/plain
      Cache-Control:
      - no-cache
      Connection:
      - close
      Content-Length:
      - '11'
    body:
      encoding: UTF-8
      string: 'Prefer: foo'
  recorded_at: Tue, 31 Oct 2023 17:12:12 GMT
recorded_with: VCR 6.2.0
